use_frameworks!

target 'CustomTextField_Example' do
  pod 'CustomTextField', :path => '../'

  target 'CustomTextField_Tests' do
    inherit! :search_paths

  end
  pod 'Toast-Swift', '~> 2.0.0'
end
